import { Given, When, Then, DataTable } from '@cucumber/cucumber';
import { expect } from '@playwright/test';
import assert from 'node:assert/strict';
import * as fs from 'node:fs';
import * as path from 'node:path';
import type { CustomWorld } from '../../support/hooks';
import {
    validateLLMResponse,
    validateStructure,
    validateKeywords,
    validateWithLLMJudge,
    type ValidationRule,
} from '../../../utils/llmValidator';
import {
    runMultiTurnConversationAndValidate,
    type TurnExpectation,
    type MatchType,
    type ChatSelectors,
} from '../../../utils/agentResponseValidator';
import { generateConversationTurns, generateExpectedIntent } from '../../../utils/turnGenerator';
import { waitForAiEvents } from '../../../utils/workflowUtils';
import { VALIDATION_RULES } from '../../../utils/validationConfig';

// ─────────────────────────────────────────────────────────────────────────────
// Load conversation turns from JSON file.
// JSON contains only user queries (userMessage or userQuery). expectedIntent is
// generated by LLM (JUDGE_API_*) when missing. Validation rules come from
// validationConfig (common file), not from the scenario or from this JSON.
// ─────────────────────────────────────────────────────────────────────────────

Given('I load conversation turns from {string}', async function (this: CustomWorld, filePath: string) {
    const baseDir = process.cwd().includes('playwright_automation')
        ? process.cwd()
        : path.join(process.cwd(), 'playwright_automation');
    const resolvedPath = path.resolve(baseDir, filePath);
    const jsonContent = fs.readFileSync(resolvedPath, 'utf-8');
    const data = JSON.parse(jsonContent) as {
        selectors?: { userQuerySelector?: string; agentResponseSelector?: string };
        turns: Array<{
            userMessage?: string;
            userQuery?: string;
            expectedResponse?: string;
            matchType?: string;
            expectedIntent?: string;
            minKeywords?: number;
        }>;
    };
    assert(Array.isArray(data.turns) && data.turns.length > 0, `JSON must have a non-empty "turns" array: ${filePath}`);

    const turnsWithIntent: Array<{
        userMessage: string;
        expectedResponse: string;
        matchType: string;
        expectedIntent?: string;
        minKeywords?: number;
    }> = [];

    for (const t of data.turns) {
        const userMessage = (t.userMessage ?? t.userQuery ?? '').trim();
        assert(userMessage, `Each turn must have "userMessage" or "userQuery": ${filePath}`);

        let expectedIntent = t.expectedIntent?.trim();
        if (!expectedIntent) {
            console.log(`  Generating expectedIntent via LLM for: "${userMessage.substring(0, 50)}..."`);
            expectedIntent = await generateExpectedIntent(userMessage);
            console.log(`  → expectedIntent: "${expectedIntent.substring(0, 60)}..."`);
        }

        turnsWithIntent.push({
            userMessage,
            expectedResponse: (t.expectedResponse ?? expectedIntent).trim(),
            matchType: (t.matchType ?? 'semantic').trim().toLowerCase(),
            expectedIntent,
            minKeywords: t.minKeywords,
        });
    }

    this.loadedTurns = turnsWithIntent;
    this.loadedSelectors = data.selectors
        ? {
            userQuerySelector: data.selectors.userQuerySelector ?? VALIDATION_RULES.userQuerySelector,
            agentResponseSelector: data.selectors.agentResponseSelector ?? VALIDATION_RULES.agentResponseSelector,
        }
        : {
            userQuerySelector: VALIDATION_RULES.userQuerySelector,
            agentResponseSelector: VALIDATION_RULES.agentResponseSelector,
        };
    this.loadedMinScore = VALIDATION_RULES.minScorePerTurn;
});

// ─────────────────────────────────────────────────────────────────────────────
// Run loaded turns and enforce minimum score
// ─────────────────────────────────────────────────────────────────────────────

Then('the agent conversation should match the loaded turns and meet minimum score {int}', async function (this: CustomWorld, minScore: number) {
    assert(this.page, 'World.page was not initialized');
    assert(this.loadedTurns?.length, 'No loaded turns. Use "I load conversation turns from ..." first.');

    const turns: TurnExpectation[] = this.loadedTurns.map((t) => ({
        userMessage: t.userMessage,
        expectedResponse: t.expectedResponse,
        matchType: (t.matchType as MatchType) || 'contains',
        expectedIntent: t.expectedIntent,
        minKeywords: t.minKeywords,
    }));

    const selectors: ChatSelectors | undefined = this.loadedSelectors
        ? {
            userQuerySelector: this.loadedSelectors.userQuerySelector,
            agentResponseSelector: this.loadedSelectors.agentResponseSelector,
        }
        : undefined;

    const result = await runMultiTurnConversationAndValidate(this.page!, turns, selectors);

    if (!result.passed && result.turnIndex !== undefined && result.results[result.turnIndex]) {
        const r = result.results[result.turnIndex];
        throw new Error(
            `Multi-turn validation failed at turn ${result.turnIndex + 1}. ` +
            `User: "${r.userMessage}". Expected: "${r.expectedResponse}". ` +
            `Actual: "${r.actualResponse.substring(0, 200)}${r.actualResponse.length > 200 ? '...' : ''}". ` +
            (r.failureReason ? `Reason: ${r.failureReason}` : '')
        );
    }
    if (!result.passed) {
        throw new Error('Multi-turn validation failed.');
    }

    for (let i = 0; i < result.results.length; i++) {
        const r = result.results[i];
        if (r.score != null && r.score < minScore) {
            throw new Error(
                `Turn ${i + 1} score ${r.score} is below minimum ${minScore}. User: "${r.userMessage}".`
            );
        }
    }
});

Then('the agent conversation should match the loaded turns', async function (this: CustomWorld) {
    assert(this.page, 'World.page was not initialized');
    assert(this.loadedTurns?.length, 'No loaded turns. Use "I load conversation turns from ..." first.');

    const minScore = this.loadedMinScore ?? 0;
    const turns: TurnExpectation[] = this.loadedTurns.map((t) => ({
        userMessage: t.userMessage,
        expectedResponse: t.expectedResponse,
        matchType: (t.matchType as MatchType) || 'contains',
        expectedIntent: t.expectedIntent,
        minKeywords: t.minKeywords,
    }));

    const selectors: ChatSelectors | undefined = this.loadedSelectors
        ? {
            userQuerySelector: this.loadedSelectors.userQuerySelector,
            agentResponseSelector: this.loadedSelectors.agentResponseSelector,
        }
        : undefined;

    const result = await runMultiTurnConversationAndValidate(this.page!, turns, selectors);

    if (!result.passed && result.turnIndex !== undefined && result.results[result.turnIndex]) {
        const r = result.results[result.turnIndex];
        throw new Error(
            `Multi-turn validation failed at turn ${result.turnIndex + 1}. ` +
            `User: "${r.userMessage}". Expected: "${r.expectedResponse}". ` +
            `Actual: "${r.actualResponse.substring(0, 200)}${r.actualResponse.length > 200 ? '...' : ''}". ` +
            (r.failureReason ? `Reason: ${r.failureReason}` : '')
        );
    }
    if (!result.passed) {
        throw new Error('Multi-turn validation failed.');
    }

    if (minScore > 0) {
        for (let i = 0; i < result.results.length; i++) {
            const r = result.results[i];
            if (r.score != null && r.score < minScore) {
                throw new Error(
                    `Turn ${i + 1} score ${r.score} is below minimum ${minScore} (from JSON). User: "${r.userMessage}".`
                );
            }
        }
    }
});

// ─────────────────────────────────────────────────────────────────────────────
// Generate conversation turns via LLM (API key from env)
// ─────────────────────────────────────────────────────────────────────────────

Given('I generate {int} conversation turns using the LLM for scenario {string}', async function (this: CustomWorld, numTurns: number, scenarioDescription: string) {
    const result = await generateConversationTurns(scenarioDescription, numTurns);
    this.loadedTurns = result.turns.map((t) => ({
        userMessage: t.userMessage,
        expectedResponse: t.expectedResponse,
        matchType: t.matchType,
        expectedIntent: t.expectedIntent,
        minKeywords: t.minKeywords,
    }));
    this.loadedSelectors = result.selectors;
});

// ─────────────────────────────────────────────────────────────────────────────
// Multi-turn conversation validation (configurable selectors)
// ─────────────────────────────────────────────────────────────────────────────

Given('I use chat user query selector {string} and agent response selector {string}', async function (this: CustomWorld, userQuerySelector: string, agentResponseSelector: string) {
    this.chatUserQuerySelector = userQuerySelector;
    this.chatAgentResponseSelector = agentResponseSelector;
});

Then('the agent conversation over {int} turns should match:', async function (this: CustomWorld, numTurns: number, dataTable: DataTable) {
    assert(this.page, 'World.page was not initialized');

    const rows = dataTable.hashes();
    const turns: TurnExpectation[] = rows.map((row: Record<string, string>) => ({
        userMessage: (row['userMessage'] ?? row['user message'] ?? '').trim(),
        expectedResponse: (row['expectedResponse'] ?? row['expected response'] ?? '').trim(),
        matchType: (row['matchType'] ?? row['match type'] ?? 'contains').trim().toLowerCase() as MatchType,
        expectedIntent: row['expectedIntent'] ?? row['expected intent'] ?? undefined,
        minKeywords: row['minKeywords'] ? parseInt(row['minKeywords'], 10) : undefined,
    }));

    if (turns.length !== numTurns) {
        throw new Error(`Table has ${turns.length} rows but step says ${numTurns} turns.`);
    }

    const selectors = (this.chatUserQuerySelector || this.chatAgentResponseSelector)
        ? { userQuerySelector: this.chatUserQuerySelector, agentResponseSelector: this.chatAgentResponseSelector }
        : undefined;

    const result = await runMultiTurnConversationAndValidate(this.page!, turns, selectors);

    if (!result.passed && result.turnIndex !== undefined && result.results[result.turnIndex]) {
        const r = result.results[result.turnIndex];
        throw new Error(
            `Multi-turn validation failed at turn ${result.turnIndex! + 1}. ` +
            `User: "${r.userMessage}". Expected: "${r.expectedResponse}". ` +
            `Actual: "${r.actualResponse.substring(0, 200)}${r.actualResponse.length > 200 ? '...' : ''}". ` +
            (r.failureReason ? `Reason: ${r.failureReason}` : '')
        );
    }
    if (!result.passed) {
        throw new Error('Multi-turn validation failed.');
    }
});

// ─────────────────────────────────────────────────────────────────────────────
// Step: Capture the agent's response text from the chat UI
// ─────────────────────────────────────────────────────────────────────────────

Then('I capture the agent response text', async function (this: CustomWorld) {
    assert(this.page, 'World.page was not initialized');

    console.log('📥 Capturing agent response text from chat UI...');

    // 1. Wait for agent to START responding (bubble must appear)
    const responseSelectors = [
        '[class*="assistant"][class*="message"]',
        '[class*="bot"][class*="message"]',
        '[class*="ai"][class*="message"]',
        '[data-role="assistant"]',
        '[class*="response"]',
        '[class*="chat-bubble"]:not([class*="user"])',
        '[class*="markdown"]',
        '[class*="message"]:not([class*="user"])',
    ];

    console.log('⏳ Waiting for agent response bubble to appear...');
    await this.page.waitForFunction((selectors) => {
        return selectors.some(s => {
            const el = document.querySelector(s);
            return el && el.textContent && el.textContent.trim().length > 3;
        });
    }, responseSelectors, { timeout: 60_000 }).catch(() => {
        console.log('⚠️ Warning: No response bubble appeared within 60s.');
    });

    // 2. Wait for typing indicator / loading spinner to disappear
    const typingIndicator = this.page.locator(
        '[class*="typing"],[class*="loading"],[class*="thinking"],[class*="spinner"],[aria-label*="loading"]'
    );
    await typingIndicator.first().waitFor({ state: 'hidden', timeout: 90_000 }).catch(() => { });

    // 3. Final wait for settling
    await this.page.waitForTimeout(3000);

    let responseText = '';
    const lastUserMessage = (this as any)._lastSentMessage?.toLowerCase() ?? '';

    // Multiple attempts to capture (in case of late streaming updates)
    for (let attempt = 0; attempt < 3; attempt++) {
        for (const selector of responseSelectors) {
            const elements = this.page.locator(selector);
            const count = await elements.count().catch(() => 0);

            if (count > 0) {
                // Check from the end (most recent message)
                for (let i = count - 1; i >= 0; i--) {
                    const el = elements.nth(i);
                    const text = (await el.textContent() ?? '').trim();
                    const lowerText = text.toLowerCase();

                    const isUserPrompt = lastUserMessage && lowerText.includes(lastUserMessage) && text.length < lastUserMessage.length + 15;
                    const isTimestamp = /^\d{1,2}:\d{2}/.test(text) && text.length < 10;

                    if (text.length >= 3 && !isUserPrompt && !isTimestamp) {
                        responseText = text;
                        // Clean up trailing timestamps if any
                        responseText = responseText.replace(/\d{1,2}:\d{2}\s*(AM|PM)?$/i, '').trim();
                        console.log(`✅ Response captured via selector "${selector}": "${responseText.substring(0, 100)}..."`);
                        break;
                    }
                }
                if (responseText) break;
            }
        }
        if (responseText) break;
        console.log(`Attempt ${attempt + 1} to capture failed, retrying...`);
        await this.page.waitForTimeout(2000);
    }

    if (!responseText) {
        throw new Error('Could not capture agent response text from the chat UI.');
    }

    (this as any)._capturedLLMResponse = responseText;
    (this as any)._lastUserMessage = (this as any)._lastSentMessage ?? 'user message';
});

// ─────────────────────────────────────────────────────────────────────────────
// Step: Structural validation
// ─────────────────────────────────────────────────────────────────────────────
Then('the LLM response should pass structural validation with min length {int}', async function (this: CustomWorld, minLength: number) {
    const response = (this as any)._capturedLLMResponse;
    assert(response, 'No captured response found');

    const rule: ValidationRule = { description: `Structural check (minLength=${minLength})`, minLength };
    const result = validateStructure(response, rule);
    if (!result.passed) {
        throw new Error(`Structural validation FAILED:\n` + result.failureReasons.map(r => `  • ${r}`).join('\n'));
    }
});

// ─────────────────────────────────────────────────────────────────────────────
// Step: Keyword validation
// ─────────────────────────────────────────────────────────────────────────────
Then('the LLM response should contain at least {int} of these keywords:', async function (this: CustomWorld, minCount: number, dataTable: DataTable) {
    const response = (this as any)._capturedLLMResponse;
    assert(response, 'No captured response found');
    const keywords = dataTable.raw().flat().map(k => k.trim()).filter(Boolean);

    const rule: ValidationRule = {
        description: `Keyword match (min ${minCount} of [${keywords.join(', ')}])`,
        requiredKeywords: keywords,
        minKeywordMatchCount: minCount,
    };

    const result = validateKeywords(response, rule);
    if (!result.passed) {
        throw new Error(`Keyword validation FAILED:\n` + result.failureReasons.map(r => `  • ${r}`).join('\n'));
    }
});

// ─────────────────────────────────────────────────────────────────────────────
// Step: No error phrases
// ─────────────────────────────────────────────────────────────────────────────
Then('the LLM response should not contain error phrases', async function (this: CustomWorld) {
    const response = (this as any)._capturedLLMResponse;
    assert(response, 'No captured response found');

    const rule: ValidationRule = { description: 'No Error Phrases' };
    const result = validateStructure(response, rule); // validateStructure already checks ERROR_INDICATORS
    if (!result.passed && result.failureReasons.some(r => r.includes('error indicators'))) {
        throw new Error(`LLM response contains error indicators.`);
    }
});

// ─────────────────────────────────────────────────────────────────────────────
// Step: LLM-as-Judge validation
// ─────────────────────────────────────────────────────────────────────────────
Then('the LLM response should be validated by LLM judge for intent {string}', async function (this: CustomWorld, expectedIntent: string) {
    const response = (this as any)._capturedLLMResponse;
    const userMessage = (this as any)._lastSentMessage ?? 'user message';
    assert(response, 'No captured response found');

    const result = await validateWithLLMJudge(response, userMessage, expectedIntent);
    if (!result.passed) {
        throw new Error(`LLM-as-Judge validation FAILED: Score ${result.score}/10 - ${result.rationale}`);
    }
});

// ─────────────────────────────────────────────────────────────────────────────
// Step: Unified validation
// ─────────────────────────────────────────────────────────────────────────────
Then('the LLM response should fully match expected intent {string} with keywords:', async function (this: CustomWorld, expectedIntent: string, dataTable: DataTable) {
    const response = (this as any)._capturedLLMResponse;
    const userMessage = (this as any)._lastSentMessage ?? 'user message';
    assert(response, 'No captured response found');
    const keywords = dataTable.raw().flat().map(k => k.trim()).filter(Boolean);

    const rule: ValidationRule = {
        description: `Full semantic validation for "${expectedIntent}"`,
        minLength: 10,
        requiredKeywords: keywords,
        minKeywordMatchCount: Math.max(1, Math.ceil(keywords.length * 0.4)),
        expectedIntent,
    };

    const result = await validateLLMResponse(response, userMessage, rule);
    if (!result.passed) {
        throw new Error(`LLM response semantic validation FAILED (score: ${result.score}/100):\n` + result.failureReasons.map(r => `  • ${r}`).join('\n'));
    }
});

// ─────────────────────────────────────────────────────────────────────────────
// Step: Agent response to a message should pass validation with Rule/Value table
// ─────────────────────────────────────────────────────────────────────────────
Then('the agent response to {string} should pass validation with:', async function (this: CustomWorld, userMessage: string, dataTable: DataTable) {
    assert(this.page, 'World.page was not initialized');

    // Send the message and track it
    (this as any)._lastSentMessage = userMessage;
    const chatInput = this.page.getByPlaceholder('Type your message here... (press enter to send)');
    await expect(chatInput).toBeVisible({ timeout: 15_000 });
    await chatInput.click();
    await chatInput.fill(userMessage);
    await chatInput.press('Enter');
    this.aiEventsCount = await waitForAiEvents(this.page, this.aiEventsCount).catch(() => this.aiEventsCount);

    // Wait for typing to finish and capture response (reuse capture logic)
    const typingIndicator = this.page.locator(
        '[class*="typing"],[class*="loading"],[class*="thinking"],[class*="spinner"],[aria-label*="loading"]'
    );
    await typingIndicator.first().waitFor({ state: 'hidden', timeout: 90_000 }).catch(() => {});
    await this.page.waitForTimeout(1500);

    const responseSelectors = [
        '[class*="assistant"][class*="message"]',
        '[class*="bot"][class*="message"]',
        '[class*="ai"][class*="message"]',
        '[data-role="assistant"]',
        '[class*="response"]',
        '[class*="chat-bubble"]:not([class*="user"])',
        '[class*="markdown"]',
        '[class*="message"]:not([class*="user"])',
    ];
    let responseText = '';
    for (const selector of responseSelectors) {
        const elements = this.page.locator(selector);
        const count = await elements.count().catch(() => 0);
        if (count > 0) {
            const el = elements.nth(count - 1);
            const text = (await el.textContent() ?? '').trim();
            if (text.length >= 3) {
                responseText = text.replace(/\d{1,2}:\d{2}\s*(AM|PM)?$/i, '').trim();
                break;
            }
        }
    }
    assert(responseText, 'Could not capture agent response text from the chat UI.');
    (this as any)._capturedLLMResponse = responseText;

    // Parse Rule/Value table into ValidationRule (skip header row if present)
    const rows = dataTable.rows();
    const ruleMap: Record<string, string> = {};
    for (const row of rows) {
        const ruleName = (row[0] ?? '').trim();
        const value = (row[1] ?? '').trim();
        if (ruleName && value && ruleName.toLowerCase() !== 'rule') ruleMap[ruleName] = value;
    }
    const minLength = ruleMap.minLength ? parseInt(ruleMap.minLength, 10) : undefined;
    const expectedIntent = ruleMap.expectedIntent ?? undefined;
    const rule: ValidationRule = {
        description: `Validation (minLength=${minLength ?? 'any'}, intent=${expectedIntent ?? 'any'})`,
        ...(minLength !== undefined && !isNaN(minLength) && { minLength }),
        ...(expectedIntent && { expectedIntent }),
    };

    const result = await validateLLMResponse(responseText, userMessage, rule);
    if (!result.passed) {
        throw new Error(
            `Agent response validation FAILED (score: ${result.score}/100):\n` +
                result.failureReasons.map((r) => `  • ${r}`).join('\n')
        );
    }
});

// ─────────────────────────────────────────────────────────────────────────────
// TRACKING
// ─────────────────────────────────────────────────────────────────────────────
When('I send and track message {string} in the chat', async function (this: CustomWorld, message: string) {
    assert(this.page, 'World.page was not initialized');
    (this as any)._lastSentMessage = message;

    const chatInput = this.page.getByPlaceholder('Type your message here... (press enter to send)');
    await expect(chatInput).toBeVisible({ timeout: 15_000 });
    await chatInput.click();
    await chatInput.fill(message);
    await chatInput.press('Enter');
    this.aiEventsCount = await waitForAiEvents(this.page, this.aiEventsCount).catch(() => this.aiEventsCount);
});
